// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwagOverflow.WPF.Data;

namespace SwagOverflow.WPF.Migrations
{
    [DbContext(typeof(SwagContext))]
    [Migration("20200404033053_M0")]
    partial class M0
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagIndexedItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Display")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValueTypeString")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("AlternateId")
                        .IsUnique();

                    b.ToTable("SwagIndexedItems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SwagIndexedItem");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Display")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueTypeString")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.HasIndex("AlternateId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("SwagItems");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SwagItem");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagSetting", b =>
                {
                    b.HasBaseType("SwagOverflow.WPF.ViewModels.SwagIndexedItem");

                    b.Property<string>("IconString")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconTypeString")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("ParentId");

                    b.HasDiscriminator().HasValue("SwagSetting");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagDataRow", b =>
                {
                    b.HasBaseType("SwagOverflow.WPF.ViewModels.SwagItem");

                    b.HasDiscriminator().HasValue("SwagDataRow");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagItemGroup", b =>
                {
                    b.HasBaseType("SwagOverflow.WPF.ViewModels.SwagItem");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SwagItemGroup");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagSettingBoolean", b =>
                {
                    b.HasBaseType("SwagOverflow.WPF.ViewModels.SwagSetting");

                    b.Property<bool>("Value")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("SwagSettingBoolean");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagSettingGroup", b =>
                {
                    b.HasBaseType("SwagOverflow.WPF.ViewModels.SwagSetting");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SwagSettingGroup");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagSettingString", b =>
                {
                    b.HasBaseType("SwagOverflow.WPF.ViewModels.SwagSetting");

                    b.Property<string>("Value")
                        .HasColumnName("SwagSettingString_Value")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SwagSettingString");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagDataTable", b =>
                {
                    b.HasBaseType("SwagOverflow.WPF.ViewModels.SwagItemGroup");

                    b.Property<string>("Columns")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("SwagDataTable");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagWindowSettingGroup", b =>
                {
                    b.HasBaseType("SwagOverflow.WPF.ViewModels.SwagSettingGroup");

                    b.HasDiscriminator().HasValue("SwagWindowSettingGroup");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagItem", b =>
                {
                    b.HasOne("SwagOverflow.WPF.ViewModels.SwagItemGroup", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("SwagOverflow.WPF.ViewModels.SwagSetting", b =>
                {
                    b.HasOne("SwagOverflow.WPF.ViewModels.SwagSettingGroup", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });
#pragma warning restore 612, 618
        }
    }
}
